import { describe, it, expect, beforeAll, afterAll } from "vitest";
import * as fs from "fs";
import * as os from "os";
import * as path from "path";
import { execFileSync } from "child_process";
import { parsePfx } from "@devcontainer-dev-certs/shared";

let opensslAvailable = false;
try {
  execFileSync("openssl", ["version"], { timeout: 5000 });
  opensslAvailable = true;
} catch {
  // openssl not available — skip the suite.
}

let fixtureDir: string;
let certPath: string;
let keyPath: string;

beforeAll(() => {
  if (!opensslAvailable) return;
  fixtureDir = fs.mkdtempSync(path.join(os.tmpdir(), "devcerts-legacy-rej-"));
  certPath = path.join(fixtureDir, "cert.pem");
  keyPath = path.join(fixtureDir, "key.pem");
  execFileSync(
    "openssl",
    [
      "req",
      "-x509",
      "-newkey",
      "rsa:2048",
      "-keyout",
      keyPath,
      "-out",
      certPath,
      "-days",
      "1",
      "-nodes",
      "-subj",
      "/CN=localhost",
    ],
    { timeout: 15000, stdio: "pipe" }
  );
});

afterAll(() => {
  if (fixtureDir) fs.rmSync(fixtureDir, { recursive: true, force: true });
});

function makeLegacyPfx(extraArgs: string[]): Buffer {
  const out = path.join(fixtureDir, `legacy-${Date.now()}.pfx`);
  execFileSync(
    "openssl",
    [
      "pkcs12",
      "-export",
      "-in",
      certPath,
      "-out",
      out,
      "-passout",
      "pass:",
      "-legacy",
      ...extraArgs,
    ],
    { timeout: 15000, stdio: "pipe" }
  );
  const bytes = fs.readFileSync(out);
  fs.unlinkSync(out);
  return bytes;
}

/**
 * The shim was deliberately removed: `parsePfx` only handles PBES2.
 * Anything older raises an actionable error. These tests pin that
 * behaviour against real legacy fixtures generated by openssl.
 */
// Platform-specific re-export recipe in the error: openssl on macOS/Linux,
// PowerShell + AES256_SHA256 on win32. Either way, the error must steer the
// user toward an actionable re-export command for the platform they're on.
const recipeRegex =
  process.platform === "win32"
    ? /CryptoAlgorithmOption AES256_SHA256/
    : /-legacy/;

describe.skipIf(!opensslAvailable)(
  "parsePfx — legacy PBE rejection",
  () => {
    it("rejects an `openssl -legacy` full PFX (3DES-encrypted key bag) with an actionable error", async () => {
      const bytes = makeLegacyPfx(["-inkey", keyPath]);
      // The cert bag is RC2-40 in this layout, so the failure could
      // happen on either layer. Either way we want the error to name
      // the offending algorithm and steer the user toward re-exporting.
      await expect(parsePfx(bytes, "")).rejects.toThrow(
        /pbeWithSHAAnd(3-KeyTripleDES|40BitRC2)-CBC/
      );
      await expect(parsePfx(bytes, "")).rejects.toThrow(recipeRegex);
    });

    it("rejects an `openssl -legacy -nokeys` cert-only PFX (RC2-40 cert bag) the same way", async () => {
      const bytes = makeLegacyPfx(["-nokeys"]);
      await expect(parsePfx(bytes, "")).rejects.toThrow(
        /pbeWithSHAAnd40BitRC2-CBC/
      );
    });
  }
);

