import * as fs from "fs";
import * as path from "path";
import { loadPfx, loadPemPair } from "@devcontainer-dev-certs/shared";
import {
  writeBundle,
  type BundleCertEntry,
} from "../bundle/writer";

export interface BundleCommandOptions {
  outDir?: string;
  containerMount?: string;
  name?: string;
  kind?: "dotnet-dev" | "user";
  noTrustInContainer?: boolean;
}

const DEFAULT_CONTAINER_MOUNT = "/host-dev-certs";

/**
 * `dcdc bundle <cert-path>` — emit a `bundle.json` referencing an
 * already-existing cert file. Useful when the cert was generated by
 * something else (e.g. `dotnet dev-certs` invoked manually, or a corporate
 * CA bundle) and the user just needs the wrapping bundle for the in-container
 * installer to consume.
 */
export async function runBundle(
  certPath: string,
  options: BundleCommandOptions
): Promise<void> {
  if (!fs.existsSync(certPath)) {
    throw new Error(`File not found: ${certPath}`);
  }

  const resolvedCertPath = path.resolve(certPath);
  const outDir = path.resolve(options.outDir ?? path.dirname(resolvedCertPath));
  const containerMount = options.containerMount ?? DEFAULT_CONTAINER_MOUNT;
  const name = options.name ?? path.basename(resolvedCertPath, path.extname(resolvedCertPath));
  const kind = options.kind ?? "user";

  const ext = resolvedCertPath.toLowerCase();
  let hostPfxPath: string | null = null;
  let hostPemPath: string;
  let hostPemKeyPath: string | null = null;
  let thumbprint: string;

  const stem = path.join(
    path.dirname(resolvedCertPath),
    path.basename(resolvedCertPath, path.extname(resolvedCertPath))
  );

  if (ext.endsWith(".pfx") || ext.endsWith(".p12")) {
    hostPfxPath = resolvedCertPath;
    const loaded = await loadPfx(resolvedCertPath);
    thumbprint = loaded.cert.thumbprintSha1;
    // Look for sibling PEM files using common naming conventions.
    const candidatePem = `${stem}.pem`;
    const candidateKey = `${stem}.key`;
    if (fs.existsSync(candidatePem)) {
      hostPemPath = candidatePem;
    } else {
      throw new Error(
        `Bundle requires a PEM cert next to the PFX. Looked for ${candidatePem}.`
      );
    }
    if (fs.existsSync(candidateKey)) hostPemKeyPath = candidateKey;
  } else {
    hostPemPath = resolvedCertPath;
    const candidateKey = `${stem}.key`;
    const keyPath = fs.existsSync(candidateKey) ? candidateKey : null;
    const loaded = loadPemPair(resolvedCertPath, keyPath);
    thumbprint = loaded.cert.thumbprintSha1;
    if (keyPath) hostPemKeyPath = candidateKey;
    // Look for sibling PFX too.
    if (fs.existsSync(`${stem}.pfx`)) hostPfxPath = `${stem}.pfx`;
  }

  const entry: BundleCertEntry = {
    name,
    kind,
    thumbprint,
    hostPfxPath,
    hostPemPath,
    hostPemKeyPath,
    trustInContainer: !options.noTrustInContainer,
  };

  fs.mkdirSync(outDir, { recursive: true });
  warnOnOutOfBundleDirPaths(entry, outDir, containerMount);
  const bundlePath = writeBundle({
    hostOutDir: outDir,
    containerMount,
    entries: [entry],
  });
  process.stderr.write(`Bundle: ${bundlePath}\n`);
  process.stderr.write(`Thumbprint: ${thumbprint}\n`);
}

/**
 * Warn when a cert file referenced by the bundle is NOT under `outDir`.
 * The writer only rewrites paths under `outDir` to the container mount;
 * paths outside are left verbatim, which means the in-container
 * installer will try to read them at their host-filesystem location —
 * something it can only do if the user has also bind-mounted that
 * location into the container. The vast majority of the time they
 * haven't, and a silently-broken bundle is worse than a noisy one.
 */
function warnOnOutOfBundleDirPaths(
  entry: BundleCertEntry,
  outDir: string,
  containerMount: string
): void {
  const candidates: Array<[string, string]> = [];
  if (entry.hostPfxPath) candidates.push(["pfxPath", entry.hostPfxPath]);
  candidates.push(["pemPath", entry.hostPemPath]);
  if (entry.hostPemKeyPath)
    candidates.push(["pemKeyPath", entry.hostPemKeyPath]);

  const resolvedOutDir = path.resolve(outDir);
  const outsideEntries = candidates.filter(([, p]) => {
    const resolved = path.resolve(p);
    return !(
      resolved === resolvedOutDir ||
      resolved.startsWith(resolvedOutDir + path.sep)
    );
  });

  if (outsideEntries.length === 0) return;

  process.stderr.write(
    `[warn] Cert files reference paths outside --out-dir (${resolvedOutDir}):\n`
  );
  for (const [field, p] of outsideEntries) {
    process.stderr.write(`         ${field}: ${p}\n`);
  }
  process.stderr.write(
    `       The bundle references absolute host paths that the in-container\n` +
      `       installer will read literally. If you only bind-mount ${resolvedOutDir}\n` +
      `       to ${containerMount}, those paths won't resolve inside the container.\n` +
      `       Either copy the cert files into --out-dir and re-run, or arrange\n` +
      `       additional mounts so the referenced paths exist container-side.\n`
  );
}
