import * as fs from "fs";
import * as path from "path";
import { loadPfx, loadPemPair } from "@devcontainer-dev-certs/shared";
import {
  writeBundle,
  type BundleCertEntry,
} from "../bundle/writer";

export interface BundleCommandOptions {
  outDir?: string;
  containerMount?: string;
  name?: string;
  kind?: "dotnet-dev" | "user";
  noTrustInContainer?: boolean;
}

const DEFAULT_CONTAINER_MOUNT = "/host-dev-certs";

/**
 * `ddc bundle <cert-path>` — emit a `bundle.json` referencing an
 * already-existing cert file. Useful when the cert was generated by
 * something else (e.g. `dotnet dev-certs` invoked manually, or a corporate
 * CA bundle) and the user just needs the wrapping bundle for the in-container
 * installer to consume.
 */
export async function runBundle(
  certPath: string,
  options: BundleCommandOptions
): Promise<void> {
  if (!fs.existsSync(certPath)) {
    throw new Error(`File not found: ${certPath}`);
  }

  const resolvedCertPath = path.resolve(certPath);
  const outDir = path.resolve(options.outDir ?? path.dirname(resolvedCertPath));
  const containerMount = options.containerMount ?? DEFAULT_CONTAINER_MOUNT;
  const name = options.name ?? path.basename(resolvedCertPath, path.extname(resolvedCertPath));
  const kind = options.kind ?? "user";

  const ext = resolvedCertPath.toLowerCase();
  let hostPfxPath: string | null = null;
  let hostPemPath: string;
  let hostPemKeyPath: string | null = null;
  let thumbprint: string;

  const stem = path.join(
    path.dirname(resolvedCertPath),
    path.basename(resolvedCertPath, path.extname(resolvedCertPath))
  );

  if (ext.endsWith(".pfx") || ext.endsWith(".p12")) {
    hostPfxPath = resolvedCertPath;
    const loaded = await loadPfx(resolvedCertPath);
    thumbprint = loaded.cert.thumbprintSha1;
    // Look for sibling PEM files using common naming conventions.
    const candidatePem = `${stem}.pem`;
    const candidateKey = `${stem}.key`;
    if (fs.existsSync(candidatePem)) {
      hostPemPath = candidatePem;
    } else {
      throw new Error(
        `Bundle requires a PEM cert next to the PFX. Looked for ${candidatePem}.`
      );
    }
    if (fs.existsSync(candidateKey)) hostPemKeyPath = candidateKey;
  } else {
    hostPemPath = resolvedCertPath;
    const candidateKey = `${stem}.key`;
    const keyPath = fs.existsSync(candidateKey) ? candidateKey : null;
    const loaded = loadPemPair(resolvedCertPath, keyPath);
    thumbprint = loaded.cert.thumbprintSha1;
    if (keyPath) hostPemKeyPath = candidateKey;
    // Look for sibling PFX too.
    if (fs.existsSync(`${stem}.pfx`)) hostPfxPath = `${stem}.pfx`;
  }

  const entry: BundleCertEntry = {
    name,
    kind,
    thumbprint,
    hostPfxPath,
    hostPemPath,
    hostPemKeyPath,
    trustInContainer: !options.noTrustInContainer,
  };

  fs.mkdirSync(outDir, { recursive: true });
  const bundlePath = writeBundle({
    hostOutDir: outDir,
    containerMount,
    entries: [entry],
  });
  process.stderr.write(`Bundle: ${bundlePath}\n`);
  process.stderr.write(`Thumbprint: ${thumbprint}\n`);
}
